users:
  pgreenld:
    password: pgreenld
  admin:
    first_name: Admin
    last_name: Admin
    password: admin
  wakibbe:
    first_name: Warren
    last_name: Kibbe
    password: demo
  chisholm:
    first_name: Rex
    last_name: Chisholm
    password: chisholm

