ClassLength:
  Max: 150
LineLength:
  Max: 175
MethodLength:
  Max: 20
AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/initializers/**
    - script/**
    - vendor/gems/**