<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load
%>

<% 
  require 'config/initializers/latticegrid'
  the_database = case LatticeGrid.the_instance
    when 'RHLCCC' then "rhlccc_latticegrid"
    when 'Feinberg' then "fsm_latticegrid"
    when 'UCSF' then "ucsf_latticegrid"
    when 'UWCCC' then "uwisc_latticegrid"
    when 'UMich' then "umich_latticegrid"
    when 'Stanford' then "stanford_latticegrid"
    when 'CINJ' then "cinj_latticegrid"
    when 'UChicago' then "uchicago_latticegrid"
    when 'UIC' then "uic_latticegrid"
    when 'AAS' then "aas_latticegrid"
    else "latticegrid"
  end
%>

# bcdatabase looks in /etc/nubic/db for a file called local_postgresql.yml in development, pstage.yml for staging, pprod.yml for production

<%= bcdb.development :local_postgresql, the_database %>
<%= bcdb.test :local_postgresql, :latticegrid_test %>
<%= bcdb.staging :pstage, the_database %>
<%= bcdb.production :pprod, the_database %>
