class InsertInvestigators < ActiveRecord::Migration
  def self.up
# left in July 2007  Investigator.create :username => "aba461", :last_name => "Barron", :first_name => "Annelise", :middle_name => "E", :email => "a-barron@northwestern.edu"
# no longer a member for 2007. Investigator.create :username => "sbe345", :last_name => "Belknap", :first_name => "Steven", :middle_name => "M", :email => "sbelknap@northwestern.edu"
# dropped summer 07   Investigator.create :username => "dad805", :last_name => "Dean", :first_name => "David", :middle_name => "", :email => "a-lam4@md.northwestern.edu"
# dropped summer 07   Investigator.create :username => "rde674", :last_name => "Derry", :first_name => "Robbin", :middle_name => "", :email => "r-derry@kellogg.northwestern.edu"
# dropped summer 07    Investigator.create :username => "reh848", :last_name => "Hendrick", :first_name => "R", :middle_name => "Edward", :email => "r-hendrick@northwestern.edu"
# dropped summer 07    Investigator.create :username => "lhi959", :last_name => "Hicke", :first_name => "Linda", :middle_name => "Anne", :pubmed_search_name => "Hicke Linda", :email => "l-hicke@northwestern.edu"
# dropped summer 07    Investigator.create :username => "tsj652", :last_name => "Jardetzky", :first_name => "Theodore", :middle_name => "S", :pubmed_search_name => "Jardetzky T S", :email => "tedj@northwestern.edu"
# left summer of 07    Investigator.create :username => "mrp881", :last_name => "Pins", :first_name => "Michael", :middle_name => "R", :email => "m-pins@northwestern.edu"
# dropped summer 07    Investigator.create :username => "rls720", :last_name => "Satcher", :first_name => "Robert", :middle_name => "L.", :email => "r-satcher@northwestern.edu"
# left summer 07   Investigator.create :username => "mss130", :last_name => "Stack", :first_name => "M.", :middle_name => "Sharon", :email => "mss130@northwestern.edu"
# dropped summer 07    Investigator.create :username => "eyx963", :last_name => "Xu", :first_name => "Eugene", :middle_name => "Y", :email => "e-xu@northwestern.edu"
# dropped summer 07    Investigator.create :username => "xya379", :last_name => "Yang", :first_name => "Ximing", :middle_name => "J.", :email => "xyang@northwestern.edu"

puts Investigator.find( :all,  :conditions => ['end_date is null or end_date >= :now', {:now => Date.today }]).length

  Investigator.create :username => "anderw", :last_name => "Anderson", :first_name => "Wayne", :middle_name => "F", :email => "wf-anderson@northwestern.edu"
  Investigator.create :username => "ava459", :last_name => "Apkarian", :first_name => "Apkar", :middle_name => "V", :pubmed_search_name => "Apkarian A V", :email => "a-apkarian@northwestern.edu"
  Investigator.create :username => "har776", :last_name => "Ardehali", :first_name => "Hossein", :middle_name => "", :email => "h-ardehali@northwestern.edu"
  Investigator.create :username => "iaa978", :last_name => "Awad", :first_name => "Issam", :middle_name => "", :email => "i-awad@northwestern.edu"
  Investigator.create :username => "vba990", :last_name => "Backman", :first_name => "Vadim", :middle_name => "", :email => "v-backman@northwestern.edu"
  Investigator.create :username => "hba435", :last_name => "Band", :first_name => "Hamid", :middle_name => "", :email => "h-band@northwestern.edu"
  Investigator.create :username => "vba436", :last_name => "Band", :first_name => "Vimla", :middle_name => "", :email => "v-band@northwestern.edu"
  Investigator.create :username => "tab926", :last_name => "Barrett", :first_name => "Terrence", :middle_name => "A", :email => "tabarrett@northwestern.edu"
  Investigator.create :username => "gjb871", :last_name => "Beitel", :first_name => "Gregory", :middle_name => "", :pubmed_search_name => "Beitel G J", :email => "beitel@northwestern.edu"
  Investigator.create :username => "cbe282", :last_name => "Bennett", :first_name => "Charles", :middle_name => "L", :email => "cbenne@northwestern.edu"
  Investigator.create :username => "benson", :last_name => "Benson", :first_name => "Al", :middle_name => "B", :pubmed_search_name => "Benson Al", :email => "a-benson@northwestern.edu"
  Investigator.create :username => "djb192", :last_name => "Bentrem", :first_name => "David", :middle_name => "Jason", :email => "dbentrem@northwestern.edu"
  Investigator.create :username => "rbe510", :last_name => "Bergan", :first_name => "Raymond", :middle_name => "C.", :email => "r-bergan@northwestern.edu"
  Investigator.create :username => "mbr791", :last_name => "Bredel", :first_name => "Markus", :middle_name => "", :email => "m-bredel@northwestern.edu"
  Investigator.create :username => "cbb511", :last_name => "Brendler", :first_name => "Charles", :middle_name => "", :email => "cbrendler@enh.org"
  Investigator.create :username => "jbl357", :last_name => "Brickner", :first_name => "Jason", :middle_name => "", :pubmed_search_name => "Brickner J H",:email => "j-brickner@northwestern.edu"
  Investigator.create :username => "mab752", :last_name => "Brown", :first_name => "Melissa", :middle_name => "A", :email => "m-brown12@northwestern.edu"
  Investigator.create :username => "ivb534", :last_name => "Budunova", :first_name => "Irina", :middle_name => "Valadimirovna", :pubmed_search_name => "Budunova I V",:email => "i-budunova@northwestern.edu"
  Investigator.create :username => "sbu768", :last_name => "Bulun", :first_name => "Serdar", :middle_name => "E", :email => "s-bulun@northwestern.edu"
  Investigator.create :username => "rca623", :last_name => "Carthew", :first_name => "Richard", :middle_name => "W", :email => "r-carthew@northwestern.edu"
  Investigator.create :username => "wjc135", :last_name => "Catalona", :first_name => "William", :middle_name => "", :email => "w-catalona@northwestern.edu"
  Investigator.create :username => "dce946", :last_name => "Cella", :first_name => "David", :middle_name => "", :email => "d-cella@northwestern.edu"
  Investigator.create :username => "dch502", :last_name => "Chakravarti", :first_name => "Debabrata", :middle_name => "", :email => "debu@northwestern.edu"
  Investigator.create :username => "cha994", :last_name => "Chandel", :first_name => "Navdeep", :middle_name => "", :email => "nav@northwestern.edu"
  Investigator.create :username => "chchang", :last_name => "Chang", :first_name => "Chih-Hung", :middle_name => "", :email => "chchang@northwestern.edu"
  Investigator.create :username => "dsc968", :last_name => "Channin", :first_name => "David", :middle_name => "S", :email => "dsc@radiology.northwestern.edu"
  Investigator.create :username => "chat", :last_name => "Chatterton", :first_name => "Robert", :middle_name => "Treat", :email => "chat@northwestern.edu"
  Investigator.create :username => "cct810", :last_name => "Cheng", :first_name => "Chonghui", :middle_name => "", :email => "chengc@northwestern.edu"
  Investigator.create :username => "ach617", :last_name => "Chenn", :first_name => "Anjen", :middle_name => "", :email => "achenn@northwestern.edu"
  Investigator.create :username => "tch554", :last_name => "Chew", :first_name => "Teng-Leong", :middle_name => "", :email => "t-chew@northwestern.edu"
  Investigator.create :username => "chisholm", :last_name => "Chisholm", :first_name => "Rex", :middle_name => "L", :pubmed_search_name => "Chisholm R L", :email => "r-chisholm@northwestern.edu"
  Investigator.create :username => "cch312", :last_name => "Chiu", :first_name => "Brian", :middle_name => "C", :pubmed_search_name => "Chiu B C", :email => "bchiu@northwestern.edu"
  Investigator.create :username => "mec985", :last_name => "Cianfrocca", :first_name => "Mary", :middle_name => "", :email => "m-cianfrocca@northwestern.edu"
  Investigator.create :username => "mcl194", :last_name => "Clayman", :first_name => "Marla", :middle_name => "", :email => "m-clayman@northwestern.edu"
  Investigator.create :username => "ccl754", :last_name => "Clevenger", :first_name => "Charles", :middle_name => "V", :pubmed_search_name => "Clevenger C V",  :email => "clevenger@northwestern.edu"
  Investigator.create :username => "llc316", :last_name => "Craft", :first_name => "Lynette", :email => "lynette-craft@northwestern.edu"
  Investigator.create :username => "sec616", :last_name => "Crawford", :first_name => "Susan", :middle_name => "E", :email => "scrawford@northwestern.edu"
  Investigator.create :username => "jdc246", :last_name => "Crispino", :first_name => "John", :middle_name => "", :email => "j-crispino@northwestern.edu"
  Investigator.create :username => "vlc718", :last_name => "Cryns", :first_name => "Vincent", :middle_name => "", :email => "v-cryns@northwestern.edu"
  Investigator.create :username => "gdi570", :last_name => "Dimri", :first_name => "Goberdhan", :middle_name => "", :email => "g-dimri@northwestern.edu"
  Investigator.create :username => "eae607", :last_name => "Eklund", :first_name => "Elizabeth", :middle_name => "", :email => "e-eklund@northwestern.edu"
  Investigator.create :username => "lle969", :last_name => "Emanuel", :first_name => "Linda", :middle_name => "L", :email => "l-emanuel@northwestern.edu"
  Investigator.create :username => "dengman", :last_name => "Engman", :first_name => "David", :middle_name => "M", :email => "d-engman@northwestern.edu"
  Investigator.create :username => "ame340", :last_name => "Evens", :first_name => "Andrew", :middle_name => "", :email => "a-evens@northwestern.edu"
  Investigator.create :username => "hfo171", :last_name => "Folsch", :first_name => "Heike", :middle_name => "", :email => "h-folsch@northwestern.edu"
  Investigator.create :username => "dmf679", :last_name => "Freymann", :first_name => "Douglas", :middle_name => "M", :email => "freymann@northwestern.edu"
  Investigator.create :username => "qga571", :last_name => "Gao", :first_name => "Qingshen", :middle_name => "", :email => "q-gao@northwestern.edu"
  Investigator.create :username => "smg645", :last_name => "Gapstur", :first_name => "Susan", :middle_name => "M", :email => "sgapstur@northwestern.edu"
  Investigator.create :username => "jga275", :last_name => "Garcia-Anoveros", :first_name => "Jaime", :middle_name => "", :pubmed_search_name => "Garcia-Anoveros J", :email => "anoveros@northwestern.edu"
  Investigator.create :username => "vge206", :last_name => "Gelfand", :first_name => "Vladimir", :middle_name => "", :email => "vgelfand@northwestern.edu"
  Investigator.create :username => "msg540", :last_name => "Goel", :first_name => "Mita", :middle_name => "", :email => "m-goel@northwestern.edu"
  Investigator.create :username => "rgoldman", :last_name => "Goldman", :first_name => "Robert", :middle_name => "David", :email => "r-goldman@northwestern.edu"
  Investigator.create :username => "sgo912", :last_name => "Goldman", :first_name => "Stewart", :middle_name => "", :email => "sgoldman@northwestern.edu"
  Investigator.create :username => "amg513", :last_name => "Gonzalez", :first_name => "Annette", :middle_name => "M", :email => "a-gonzalez2@northwestern.edu"
  Investigator.create :username => "clg879", :last_name => "Goolsby", :first_name => "Charles", :middle_name => "Lewis", :pubmed_search_name => "Goolsby C L", :email => "c-goolsby@northwestern.edu"
  Investigator.create :username => "ligordon", :last_name => "Gordon", :first_name => "Leo", :middle_name => "I", :email => "l-gordon@northwestern.edu"
  Investigator.create :username => "cgo790", :last_name => "Gottardi", :first_name => "Cara", :middle_name => "", :email => "c-gottardi@northwestern.edu"
  Investigator.create :username => "wjg", :last_name => "Gradishar", :first_name => "William", :middle_name => "J", :email => "w-gradishar@northwestern.edu"
  Investigator.create :username => "kgreen", :last_name => "Green", :first_name => "Kathleen", :middle_name => "Janee", :email => "kgreen@northwestern.edu"
  Investigator.create :username => "sgr302", :last_name => "Grimm", :first_name => "Sean", :middle_name => "", :email => "sean-grimm@northwestern.edu"
  Investigator.create :username => "pgr517", :last_name => "Grippo", :first_name => "Paul", :middle_name => "", :email => "p-grippo@northwestern.edu"
  Investigator.create :username => "agr714", :last_name => "Gross", :first_name => "Adrian", :middle_name => "", :email => "a-gross@northwestern.edu"
  Investigator.create :username => "jgu906", :last_name => "Guitart", :first_name => "Joan", :middle_name => "", :email => "j-guitart@northwestern.edu"
  Investigator.create :username => "eha003", :last_name => "Hahn", :first_name => "Elizabeth", :middle_name => "A.", :email => "e-hahn@northwestern.edu"
  Investigator.create :username => "nmh249", :last_name => "Hansen", :first_name => "Nora", :middle_name => "", :email => "nhansen@nmh.org"
  Investigator.create :username => "xhe850", :last_name => "He", :first_name => "Xiaolin", :middle_name => "", :pubmed_limit_to_institution => true, :email => "x-he@northwestern.edu"
  Investigator.create :username => "awh", :last_name => "Heinemann", :first_name => "Allen", :middle_name => "", :email => "a-heinemann@northwestern.edu"
  Investigator.create :username => "mjh531", :last_name => "Hendrix", :first_name => "Mary", :middle_name => "", :email => "mjchendrix@childrensmemorial.org"
  Investigator.create :username => "dhj204", :last_name => "Ho", :first_name => "Dean", :middle_name => "", :email => "d-ho@northwestern.edu"
  Investigator.create :username => "bmh176", :last_name => "Hoffman", :first_name => "Brian", :middle_name => "M", :email => "bmh@northwestern.edu"
  Investigator.create :username => "holmgren", :last_name => "Holmgren", :first_name => "Robert", :middle_name => "A", :email => "r-holmgren@northwestern.edu"
  Investigator.create :username => "tjh769", :last_name => "Hope", :first_name => "Thomas", :middle_name => "", :email => "thope@northwestern.edu"
  Investigator.create :username => "cho741", :last_name => "Horvath", :first_name => "Curt", :middle_name => "", :email => "horvath@northwestern.edu"
  Investigator.create :username => "lho444", :last_name => "Hou", :first_name => "Lifang", :middle_name => "", :email => "l-hou@northwestern.edu"
  Investigator.create :username => "shu683", :last_name => "Huang", :first_name => "Sui", :middle_name => "", :email => "s-huang2@northwestern.edu"
  Investigator.create :username => "mah834", :last_name => "Hummel", :first_name => "Mary", :middle_name => "", :pubmed_search_name => "Hummel M", :pubmed_limit_to_institution => true, :email => "m-hummel@northwestern.edu"
  Investigator.create :username => "philip", :last_name => "Iannaccone", :first_name => "Philip", :middle_name => "M", :pubmed_search_name => "Iannaccone P", :email => "pmi@northwestern.edu"
  Investigator.create :username => "kiw253", :last_name => "Iwasaki", :first_name => "Kouichi", :middle_name => "", :email => "k-iwasaki@northwestern.edu"
  Investigator.create :username => "djacobsohn@childrensmemorial.org", :last_name => "Jacobsohn", :first_name => "David", :middle_name => "", :email => "djacobsohn@childrensmemorial.org"
  Investigator.create :username => "jameson", :last_name => "Jameson", :first_name => "James", :middle_name => "Larry", :pubmed_search_name => "Jameson J L", :email => "ljameson@northwestern.edu"
  Investigator.create :username => "jsj360", :last_name => "Jeruss", :first_name => "Jacqueline", :middle_name => "Sara", :pubmed_search_name => "Jeruss J S", :email => "jjeruss@nmh.org"
  Investigator.create :username => "jjones", :last_name => "Jones", :first_name => "Jonathan", :middle_name => "C", :pubmed_search_name => "Jones J C", :pubmed_limit_to_institution => true, :email => "j-jones3@northwestern.edu"
  Investigator.create :username => "vgk331", :last_name => "Kaklamani", :first_name => "Virginia", :middle_name => "Georgia", :email => "v-kaklamani@md.northwestern.edu"
  Investigator.create :username => "hidk", :last_name => "Kamp", :first_name => "David", :middle_name => "William", :email => "d-kamp@northwestern.edu"
  Investigator.create :username => "gsk116", :last_name => "Kansas", :first_name => "Geoffrey", :middle_name => "S.", :pubmed_search_name => "Kansas G S", :email => "gsk@northwestern.edu"
  Investigator.create :username => "klk083", :last_name => "Kaul", :first_name => "Karen", :middle_name => "L", :pubmed_search_name => "Kaul K", :email => "k-kaul@northwestern.edu"
  Investigator.create :username => "jak138", :last_name => "Kessler", :first_name => "John", :middle_name => "A", :pubmed_search_name => "Kessler J A", :email => "jakessler@northwestern.edu"
  Investigator.create :username => "zellis@childrensmemorial.org", :last_name => "Khalkhali-Ellis", :first_name => "Zhila", :middle_name => "", :pubmed_search_name => "Khalkhali-Ellis Z", :email => "zellis@childrensmemorial.org"
  Investigator.create :username => "skh770", :last_name => "Khan", :first_name => "Seema", :middle_name => "Ahsan", :email => "s-khan2@northwestern.edu"
  Investigator.create :username => "jdk627", :last_name => "Khandekar", :first_name => "Janardan", :middle_name => "D", :pubmed_search_name => "Khandekar J D", :email => "j-khandekar@northwestern.edu"
  Investigator.create :username => "mki094", :last_name => "Kibbe", :first_name => "Melina", :middle_name => "", :email => "m-kibbe@md.northwestern.edu"
  Investigator.create :username => "wakibbe", :last_name => "Kibbe", :first_name => "Warren", :middle_name => "", :email => "wakibbe@northwestern.edu"
  Investigator.create :username => "jjk965", :last_name => "Kim", :first_name => "Ji-Yong", :middle_name => "Julie", :pubmed_search_name => "Kim J J", :pubmed_limit_to_institution => true, :email => "j-kim4@northwestern.edu"
  Investigator.create :username => "dkirsch@childrensmemorial.org", :last_name => "Kirschmann", :first_name => "Dawn", :middle_name => "", :email => "dkirsch@childrensmemorial.org"
  Investigator.create :username => "hki884", :last_name => "Kiyokawa", :first_name => "Hiroaki", :middle_name => "", :email => "kiyokawa@northwestern.edu"
  Investigator.create :username => "mkletzel", :last_name => "Kletzel", :first_name => "Morris", :middle_name => "", :email => "mkletzel@northwestern.edu"
  Investigator.create :username => "petekopp", :last_name => "Kopp", :first_name => "Peter", :middle_name => "", :email => "p-kopp@northwestern.edu"
  Investigator.create :username => "jkramer", :last_name => "Kramer", :first_name => "James", :middle_name => "M",  :pubmed_search_name => "Kramer J M", :pubmed_limit_to_institution => true, :email => "jkramer@northwestern.edu"
  Investigator.create :username => "nkrett", :last_name => "Krett", :first_name => "Nancy", :middle_name => "L", :pubmed_search_name => "Krett N L", :email => "n-krett@northwestern.edu"
  Investigator.create :username => "tkuzel", :last_name => "Kuzel", :first_name => "Timothy", :middle_name => "Michael", :email => "t-kuzel@northwestern.edu"
  Investigator.create :username => "cbl517", :last_name => "LaBonne", :first_name => "Carole", :middle_name => "B", :pubmed_search_name => "LaBonne C", :email => "clabonne@northwestern.edu"
  Investigator.create :username => "mel447", :last_name => "Lacouture", :first_name => "Mario", :middle_name => "", :email => "m-lacouture@northwestern.edu"
  Investigator.create :username => "jla782", :last_name => "Lai", :first_name => "Jin-shei", :middle_name => "", :email => "js-lai@northwestern.edu"
  Investigator.create :username => "lal", :last_name => "Laimins", :first_name => "Laimonis", :middle_name => "A",  :pubmed_search_name => "Laimins L A", :email => "l-laimins@northwestern.edu"
  Investigator.create :username => "ralamb", :last_name => "Lamb", :first_name => "Robert", :middle_name => "A", :email => "ralamb@northwestern.edu"
  Investigator.create :username => "mll903", :last_name => "Lamm", :first_name => "Marilyn", :middle_name => "",  :pubmed_search_name => "Lamm M L", :email => "mlamm@northwestern.edu"
  Investigator.create :username => "chunglee", :last_name => "Lee", :first_name => "Chung", :middle_name => "", :pubmed_limit_to_institution => true, :email => "c-lee7@northwestern.edu"
  Investigator.create :username => "rleikin", :last_name => "Leikin", :first_name => "Robin", :middle_name => "", :email => "rleikin@northwestern.edu"
  Investigator.create :username => "leis", :last_name => "Leis", :first_name => "Jonathan", :middle_name => "Peter", :pubmed_search_name => "Leis J", :pubmed_limit_to_institution => true, :email => "j-leis@northwestern.edu"
  Investigator.create :username => "asl648", :last_name => "Levenson", :first_name => "Anait", :middle_name => "S", :pubmed_search_name => "Levenson A S", :email => "a-levenson@northwestern.edu"
  Investigator.create :username => "vvl690", :last_name => "Levenson", :first_name => "Victor", :middle_name => "V", :pubmed_search_name => "Levenson V V", :email => "levenson@northwestern.edu"
  Investigator.create :username => "lli494", :last_name => "Li", :first_name => "Liming", :middle_name => "", :email => "limingli@northwestern.edu"
  Investigator.create :username => "xli714", :last_name => "Li", :first_name => "Xu", :middle_name => "", :pubmed_limit_to_institution => true, :email => "xuli@northwestern.edu" 
  Investigator.create :username => "jdl533", :last_name => "Licht", :first_name => "Jonathan", :middle_name => "", :email => "j-licht@northwestern.edu"
  Investigator.create :username => "dlinzer", :last_name => "Linzer", :first_name => "Daniel", :middle_name => "I", :pubmed_search_name => "Linzer D I", :email => "dlinzer@northwestern.edu"
  Investigator.create :username => "gylocker", :last_name => "Locker", :first_name => "Gershon", :middle_name => "Y", :pubmed_search_name => "Locker G Y",  :email => "gylocker@northwestern.edu"
  Investigator.create :username => "logemann", :last_name => "Logemann", :first_name => "Jerilyn", :middle_name => "A", :pubmed_search_name => "Logemann J A", :email => "j-logemann@northwestern.edu"
  Investigator.create :username => "jlomas", :last_name => "Lomasney", :first_name => "Jon", :middle_name => "W", :pubmed_search_name => "Lomasney J W", :email => "j-lomasney@northwestern.edu"
  Investigator.create :username => "rlong", :last_name => "Longnecker", :first_name => "Richard", :middle_name => "M", :pubmed_search_name => "Longnecker R", :email => "r-longnecker@northwestern.edu"
  Investigator.create :username => "zlu119", :last_name => "Lu", :first_name => "Zhidong", :middle_name => "Nick", :pubmed_search_name => "Lu N Z", :email => "nickzlu@northwestern.edu"
  Investigator.create :username => "rlu628", :last_name => "Lupu", :first_name => "Ruth", :middle_name => "", :email => "r-lupu@northwestern.edu"
  Investigator.create :username => "grm883", :last_name => "MacVicar", :first_name => "Gary", :middle_name => "", :email => "g-macvicar@northwestern.edu"
  Investigator.create :username => "makoul", :last_name => "Makoul", :first_name => "Gregory", :middle_name => "Thomas", :pubmed_search_name => "Makoul G", :email => "makoul@northwestern.edu"
  Investigator.create :username => "mcm469", :last_name => "Martini", :first_name => "Mary", :middle_name => "C", :email => "m-martini@northwestern.edu"
  Investigator.create :username => "ama189", :last_name => "Matouschek", :first_name => "Andreas", :middle_name => "T", :pubmed_search_name => "Matouschek A", :email => "matouschek@northwestern.edu"
  Investigator.create :username => "kemayo", :last_name => "Mayo", :first_name => "Kelly", :middle_name => "Edward", :pubmed_search_name => "Mayo K E", :email => "k-mayo@northwestern.edu"
  Investigator.create :username => "tjm007", :last_name => "McGarry", :first_name => "Thomas", :middle_name => "J", :pubmed_search_name => "McGarry T J", :email => "t-mcgarry@northwestern.edu"
  Investigator.create :username => "jmm392", :last_name => "McKoy", :first_name => "June", :middle_name => "", :email => "j-mckoy@md.northwestern.edu"
  Investigator.create :username => "ktm", :last_name => "McVary", :first_name => "Kevin", :middle_name => "T", :email => "k-mcvary@northwestern.edu"
  Investigator.create :username => "tjm604", :last_name => "Meade", :first_name => "Thomas", :middle_name => "J", :email => "tmeade@northwestern.edu"
  Investigator.create :username => "jme662", :last_name => "Mehta", :first_name => "Jayesh", :middle_name => "", :email => "j-mehta@northwestern.edu"
  Investigator.create :username => "rjm821", :last_name => "Miller", :first_name => "Richard", :middle_name => "J", :email => "r-miller10@northwestern.edu"
  Investigator.create :username => "wmmiller", :last_name => "Miller", :first_name => "William", :middle_name => "M", :pubmed_search_name => "Miller W M", :pubmed_limit_to_institution => true, :email => "wmmiller@northwestern.edu"
  Investigator.create :username => "cam493", :last_name => "Mirkin", :first_name => "Chad", :middle_name => "A", :email => "c-mirkin@northwestern.edu"
  Investigator.create :username => "bmi218", :last_name => "Mittal", :first_name => "Bharat", :middle_name => "B", :pubmed_search_name => "Mittal B B", :email => "bmittal@nmh.org"
  Investigator.create :username => "dcm863", :last_name => "Mohr", :first_name => "David", :middle_name => "", :email => "d-mohr@northwestern.edu"
  Investigator.create :username => "mondrago", :last_name => "Mondragon", :first_name => "Alfonso", :middle_name => "", :pubmed_search_name => "Mondragon A", :pubmed_limit_to_institution => true, :email => "a-mondragon@northwestern.edu"
  Investigator.create :username => "morimoto", :last_name => "Morimoto", :first_name => "Richard", :middle_name => "I", :pubmed_search_name => "Morimoto R I", :email => "r-morimoto@northwestern.edu"
  Investigator.create :username => "cinnmosk", :last_name => "Moskal", :first_name => "Joseph", :middle_name => "", :email => "j-moskal@northwestern.edu"
  Investigator.create :username => "fmm757", :last_name => "Mulcahy", :first_name => "Mary", :middle_name => "Frances", :email => "m-mulcahy@northwestern.edu"
  Investigator.create :username => "hgm988", :last_name => "Munshi", :first_name => "Hidayatullah", :middle_name => "G",:pubmed_search_name => "Munshi H G", :email => "h-munshi@md.northwestern.edu"
  Investigator.create :username => "tam011", :last_name => "Mustoe", :first_name => "Thomas", :middle_name => "A", :email => "t-mustoe@northwestern.edu"
  Investigator.create :username => "stn424", :last_name => "Nguyen", :first_name => "SonBinh", :middle_name => "T", :email => "stn@northwestern.edu"
  Investigator.create :username => "tvo", :last_name => "O'Halloran", :first_name => "Thomas", :middle_name => "V", :pubmed_search_name => "O'Halloran T V ", :email => "t-ohalloran@northwestern.edu"
  Investigator.create :username => "aor766", :last_name => "Omary", :first_name => "Reed", :middle_name => "", :email => "reed@northwestern.edu"
  Investigator.create :username => "tou767", :last_name => "Ouchi", :first_name => "Toru", :middle_name => "", :email => "t-ouchi@northwestern.edu"
  Investigator.create :username => "jpa590", :last_name => "Paice", :first_name => "Judith", :middle_name => "", :email => "j-paice@northwestern.edu"
  Investigator.create :username => "apaller", :last_name => "Paller", :first_name => "Amy", :middle_name => "", :email => "apaller@northwestern.edu"
  Investigator.create :username => "etp353", :last_name => "Papoutsakis", :first_name => "Eleftherios", :middle_name => "", :email => "e-paps@northwestern.edu"
  Investigator.create :username => "bpa601", :last_name => "Pasche", :first_name => "Boris", :middle_name => "", :email => "b-pasche@northwestern.edu"
  Investigator.create :username => "jdp561", :last_name => "Patel", :first_name => "Jyoti", :middle_name => "", :email => "jd-patel@northwestern.edu"
  Investigator.create :username => "jpe670", :last_name => "Pelling", :first_name => "Jill", :middle_name => "", :email => "j-pelling@northwestern.edu"
  Investigator.create :username => "ejp866", :last_name => "Perlman", :first_name => "Elizabeth", :middle_name => "J", :email => "eperlman@childrensmemorial.org"
  Investigator.create :username => "lcp123", :last_name => "Peterson", :first_name => "LoAnn", :middle_name => "Charlotte", :email => "loannc@northwestern.edu"
  Investigator.create :username => "schallma", :last_name => "Phillips", :first_name => "Benette", :middle_name => "", :email => "schallma@northwestern.edu"
  Investigator.create :username => "pinto", :last_name => "Pinto", :first_name => "Lawrence", :middle_name => "H", :email => "larry-pinto@northwestern.edu"
  Investigator.create :username => "lpl530", :last_name => "Platanias", :first_name => "Leonidas", :middle_name => "", :email => "l-platanias@northwestern.edu"
  Investigator.create :username => "rmp158", :last_name => "Pope", :first_name => "Richard", :middle_name => "M", :pubmed_search_name => "Pope R M", :email => "rmp158@northwestern.edu"
  Investigator.create :username => "cpu125", :last_name => "Pugh", :first_name => "Carla", :middle_name => "", :email => "drpugh@northwestern.edu"
  Investigator.create :username => "rademake", :last_name => "Rademaker", :first_name => "Alfred", :middle_name => "W", :pubmed_search_name => "Rademaker A W", :email => "rademaker@northwestern.edu"
  Investigator.create :username => "ira124", :last_name => "Radhakrishnan", :first_name => "Ishwar", :middle_name => "", :pubmed_search_name => "Radhakrishnan I", :email => "i-radhakrishnan@northwestern.edu"
  Investigator.create :username => "jra428", :last_name => "Raizer", :first_name => "Jeffrey", :middle_name => "", :email => "j-raizer@northwestern.edu"
  Investigator.create :username => "smr258", :last_name => "Rao", :first_name => "M", :middle_name => "Sambasiva",  :pubmed_search_name => "Rao M S", :pubmed_limit_to_institution => true, :email => "s-rao@northwestern.edu"
  Investigator.create :username => "jkreddy", :last_name => "Reddy", :first_name => "Janardan", :middle_name => "K", :pubmed_search_name => "Reddy J K", :pubmed_limit_to_institution => true,  :email => "jkreddy@northwestern.edu"
  Investigator.create :username => "ser710", :last_name => "Rice", :first_name => "Sarah", :middle_name => "E", :email => "s-rice@northwestern.edu"
  Investigator.create :username => "jkr320", :last_name => "Robinson", :first_name => "June", :middle_name => "", :email => "wtbjkr@rcn.com"
  Investigator.create :username => "grodriguez@enh.org", :last_name => "Rodriguez", :first_name => "Gustavo", :middle_name => "", :email => "grodriguez@enh.org", :pubmed_limit_to_institution => true
  Investigator.create :username => "str", :last_name => "Rosen", :first_name => "Steven", :middle_name => "T",  :pubmed_search_name => "Rosen S T", :email => "s-rosen@northwestern.edu"
  Investigator.create :username => "aro764", :last_name => "Rosenzweig", :first_name => "Amy", :middle_name => "C", :email => "amyr@northwestern.edu"
  Investigator.create :username => "roy056", :last_name => "Roy", :first_name => "Hemant", :middle_name => "", :email => "h-roy@northwestern.edu"
  Investigator.create :username => "wru362", :last_name => "Rubinstein", :first_name => "Wendy", :middle_name => "", :email => "w-rubinstein@northwestern.edu"
  Investigator.create :username => "mkr389", :last_name => "Rundell", :first_name => "M", :middle_name => "Kathleen", :pubmed_search_name => "Rundell K", :pubmed_limit_to_institution => true, :email => "krundell@northwestern.edu"
  Investigator.create :username => "rsa645", :last_name => "Salem", :first_name => "Riad", :middle_name => "", :email => "r-salem@northwestern.edu"
  Investigator.create :username => "rsc248", :last_name => "Scarpulla", :first_name => "Richard", :middle_name => "C", :pubmed_search_name => "Scarpulla R C", :email => "rsc248@northwestern.edu"
  Investigator.create :username => "ajs351", :last_name => "Schaeffer", :first_name => "Anthony", :middle_name => "J", :email => "ajschaeffer@northwestern.edu"
  Investigator.create :username => "kas821", :last_name => "Scheidt", :first_name => "Karl", :middle_name => "A", :email => "scheidt@northwestern.edu"
  Investigator.create :username => "jcs643", :last_name => "Schink", :first_name => "Julian", :middle_name => "", :email => "jschink@nmff.org"
  Investigator.create :username => "hws124", :last_name => "Schnaper", :first_name => "Howard", :middle_name => "William", :pubmed_search_name => "Schnaper H W",:email => "schnaper@northwestern.edu"
  Investigator.create :username => "pts987", :last_name => "Schumacker", :first_name => "Paul", :middle_name => "", :email => "p-schumacker@northwestern.edu"
  Investigator.create :username => "res992", :last_name => "Seftor", :first_name => "Richard", :middle_name => "", :email => "rseftor@childrensmemorial.org"
  Investigator.create :username => "spr737", :last_name => "Seth", :first_name => "Prem", :middle_name => "", :email => "pseth@northwestern.edu"
  Investigator.create :username => "lds384", :last_name => "Shea", :first_name => "Lonnie", :middle_name => "D", :email => "l-shea@northwestern.edu"
  Investigator.create :username => "dhs380", :last_name => "Shevrin", :first_name => "Daniel", :middle_name => "H", :pubmed_search_name => "Shevrin D H", :email => "d-shevrin@northwestern.edu"
  Investigator.create :username => "rbs599", :last_name => "Silverman", :first_name => "Richard", :middle_name => "B", :pubmed_search_name => "Silverman R B", :email => "r-silverman@northwestern.edu"
  Investigator.create :username => "dks845", :last_name => "Singh", :first_name => "Diljeet", :middle_name => "", :email => "d-singh2@northwestern.edu"
  Investigator.create :username => "ssi694", :last_name => "Singhal", :first_name => "Seema", :middle_name => "", :email => "s-singhal@northwestern.edu"
  Investigator.create :username => "radman", :last_name => "Small", :first_name => "William", :middle_name => "", :pubmed_search_name => "Small W Jr", :email => "w-small@northwestern.edu"
  Investigator.create :username => "gas611", :last_name => "Smith", :first_name => "Greg", :middle_name => "Allan", :email => "g-smith3@northwestern.edu"
  Investigator.create :username => "msp325", :last_name => "Soares", :first_name => "Marcelo", :middle_name => "", :email => "mbsoares@childrensmemorial.org"
  Investigator.create :username => "ejs760", :last_name => "Sontheimer", :first_name => "Erik", :middle_name => "J", :email => "erik@northwestern.edu"
  Investigator.create :username => "pgspear", :last_name => "Spear", :first_name => "Patricia", :middle_name => "Gail", :email => "p-spear@northwestern.edu"
  Investigator.create :username => "bjs962", :last_name => "Spring", :first_name => "Bonnie", :middle_name => "", :email => "bspring@northwestern.edu"
  Investigator.create :username => "pls643", :last_name => "Stein", :first_name => "Paul", :middle_name => "", :email => "p-stein2@northwestern.edu", :pubmed_limit_to_institution => true
  Investigator.create :username => "pstern", :last_name => "Stern", :first_name => "Paula", :middle_name => "H", :pubmed_search_name => "Stern P H", :email => "p-stern@northwestern.edu"
  Investigator.create :username => "sis997", :last_name => "Stupp", :first_name => "Samuel", :middle_name => "Isaac", :pubmed_search_name => "Stupp S I", :email => "s-stupp@northwestern.edu"
  Investigator.create :username => "mstalamo", :last_name => "Talamonti", :first_name => "Mark", :middle_name => "S", :email => "mtalamonti@enh.org"
  Investigator.create :username => "mtallman", :last_name => "Tallman", :first_name => "Martin", :middle_name => "S", :email => "m-tallman@northwestern.edu"
  Investigator.create :username => "bayar", :last_name => "Thimmapaya", :first_name => "Bayar", :middle_name => "", :pubmed_search_name => "Thimmapaya B", :email => "b-thimmapaya@northwestern.edu"
  Investigator.create :username => "rtj232", :last_name => "Thomson", :first_name => "Regan", :middle_name => "James", :email => "r-thomson@northwestern.edu"
  Investigator.create :username => "wto456", :last_name => "Tourtellotte", :first_name => "Warren", :middle_name => "Gerard",  :pubmed_search_name => "Tourtellotte W G", :email => "warren@northwestern.edu"
  Investigator.create :username => "ouh865", :last_name => "Uhlenbeck", :first_name => "Olke", :middle_name => "", :email => "o-uhlenbeck@northwestern.edu"
  Investigator.create :username => "vaneldik", :last_name => "Van Eldik", :first_name => "Linda", :middle_name => "Jo", :pubmed_search_name => "Van Eldik L J", :email => "vaneldik@northwestern.edu"
  Investigator.create :username => "lvanhorn", :last_name => "Van Horn", :first_name => "Linda", :middle_name => "V", :pubmed_search_name => "Van Horn Linda", :email => "lvanhorn@northwestern.edu"
  Investigator.create :username => "jva128", :last_name => "Varga", :first_name => "John", :middle_name => "", :email => "j-varga@northwestern.edu"
  Investigator.create :username => "tav464", :last_name => "Volpe", :first_name => "Tom", :middle_name => "", :email => "t-volpe2@northwestern.edu"
  Investigator.create :username => "tvo743", :last_name => "Volpe", :first_name => "Timothy", :middle_name => "", :email => "t-volpe@northwestern.edu"
  Investigator.create :username => "olgavolp", :last_name => "Volpert", :first_name => "Olga", :middle_name => "", :email => "olgavolp@northwestern.edu"
  Investigator.create :username => "vonroenn", :last_name => "Von Roenn", :first_name => "Jamie", :middle_name => "Hayden", :pubmed_search_name => "Von Roenn J H", :email => "j-vonroenn@northwestern.edu"
  Investigator.create :username => "lwa710", :last_name => "Wagner", :first_name => "Lynne", :middle_name => "I", :email => "lwagner@northwestern.edu"
  Investigator.create :username => "rwali@enh.org", :last_name => "Wali", :first_name => "Ramesh", :middle_name => "", :email => "rwali@enh.org"
  Investigator.create :username => "dow641", :last_name => "Walterhouse", :first_name => "David", :middle_name => "O", :pubmed_search_name => "Walterhouse D O", :email => "d-walterhouse@northwestern.edu"
  Investigator.create :username => "smw702", :last_name => "Wang", :first_name => "San", :middle_name => "Ming,", :pubmed_search_name => "Wang San Ming", :email => "swang1@northwestern.edu"
  Investigator.create :username => "xwa833", :last_name => "Wang", :first_name => "Xiao-Qi", :middle_name => "", :email => "x-wang1@northwestern.edu"
  Investigator.create :username => "xwa760", :last_name => "Wang", :first_name => "Xiaozhong", :middle_name => "", :email => "awang@northwestern.edu"
  Investigator.create :username => "watterso", :last_name => "Watterson", :first_name => "Daniel", :middle_name => "Martin",  :pubmed_search_name => "Watterson D M", :email => "m-watterson@northwestern.edu"
  Investigator.create :username => "elw264", :last_name => "Weiss", :first_name => "Eric", :middle_name => "", :email => "elweiss@northwestern.edu"
  Investigator.create :username => "saweitz", :last_name => "Weitzman", :first_name => "Sigmund", :middle_name => "A", :pubmed_search_name => "Weitzman S A", :email => "s-weitzman@northwestern.edu"
  Investigator.create :username => "jwi243", :last_name => "Widom", :first_name => "Jonathan", :middle_name => "", :pubmed_search_name => "Widom J", :email => "j-widom@northwestern.edu"
  Investigator.create :username => "swi249", :last_name => "Winandy", :first_name => "Susan", :middle_name => "", :email => "s-winandy@northwestern.edu"
  Investigator.create :username => "jwinter", :last_name => "Winter", :first_name => "Jane", :middle_name => "Norma", :email => "j-winter@northwestern.edu"
  Investigator.create :username => "mwo292", :last_name => "Wolf", :first_name => "Michael", :middle_name => "S", :email => "mswolf@northwestern.edu"
  Investigator.create :username => "gew111", :last_name => "Woloschak", :first_name => "Gayle", :middle_name => "", :pubmed_search_name => "Woloschak G",  :email => "g-woloschak@northwestern.edu"
  Investigator.create :username => "tkw086", :last_name => "Woodruff", :first_name => "Teresa", :middle_name => "K", :pubmed_search_name => "Woodruff T K", :email => "tkw@northwestern.edu"
  Investigator.create :username => "jwn341", :last_name => "Wu", :first_name => "Jane", :middle_name => "", :email => "jane-wu@northwestern.edu"
  Investigator.create :username => "gya826", :last_name => "Yang", :first_name => "Guang-Yu", :middle_name => "", :email => "g-yang@northwestern.edu"
  Investigator.create :username => "nya489", :last_name => "Yaseen", :first_name => "Nabeel", :middle_name => "", :email => "n-yaseen@northwestern.edu"
  Investigator.create :username => "awy956", :last_name => "Yasko", :first_name => "Alan", :middle_name => "", :email => "a-yasko@northwestern.edu"
  Investigator.create :username => "ssy450", :last_name => "Yoo", :first_name => "Simon", :middle_name => "", :email => "simon-yoo@northwestern.edu"
  Investigator.create :username => "kjy291", :last_name => "Yost", :first_name => "Kathleen", :middle_name => "", :email => "kyost@enh.org"
  Investigator.create :username => "syo450", :last_name => "Yount", :first_name => "Susan", :middle_name => "", :email => "s-yount@northwestern.edu"
  Investigator.create :username => "mzh511", :last_name => "Zhang", :first_name => "Ming", :middle_name => "",  :pubmed_search_name => "Zhang M", :pubmed_limit_to_institution => true, :email => "m-zhang@northwestern.edu"
  Investigator.create :username => "yijun", :last_name => "Zhu", :first_name => "Yijun", :middle_name => "", :email => "y-zhu2@northwestern.edu"
#for Fred
#Investigator.create :username => "fake18", :last_name => "Chmiel", :first_name => "Joan", :middle_name => "", :pubmed_search_name => "chmiel js[auth] or chmiel, joan", :email => "jchmiel@northwestern.edu"  
#Investigator.create :username => "fake19", :last_name => "Scholtens", :first_name => "Denise", :middle_name => "",  :email => "dscholtens@northwestern.edu"
#Investigator.create :username => "fake20", :last_name => "Jovanovic", :first_name => "Borko", :middle_name => "", :pubmed_search_name => "Jovanovic BD[Author]  or Jovanovic, Borko",  :email => "borko@northwestern.edu"
#Investigator.create :username => "fake21", :last_name => "Huang", :first_name => "Chiang-Ching", :middle_name => "", :email => "huangcc@northwestern.edu"

  puts Investigator.find( :all,  :conditions => ['end_date is null or end_date >= :now', {:now => Date.today }]).length

  end

  def self.down
    Investigator.delete_all 
  end
end
